In [2]:
import pandas as pd 
import numpy as np

In [8]:
s=pd.Series()

C:\Users\DELL\AppData\Local\Temp\ipykernel_3484\3677558548.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s=pd.Series()


In [16]:
intArr = np.arange(10)

sArr = np.array(['a', 'b','c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])

intSer = pd.Series(data = intArr )
intSer

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [17]:
ser = pd.Series(data=intArr, index=['a', 'b','c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print(ser)

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
i    8
j    9
dtype: int32


In [18]:
# Create Series using dictionary

dictData = {'a' : 0., 'b' : 1., 'c' : 2.}

s = pd.Series(data = dictData)
print(s)

a    0.0
b    1.0
c    2.0
dtype: float64


In [19]:
# Create Series using dictionary and passing index 
dictData = {'a' : 0., 'b' : 1., 'c' : 2.}
s = pd.Series(data = dictData, index=[0,1,2])
print(s)

0   NaN
1   NaN
2   NaN
dtype: float64


In [20]:
dictData = {'a' : 0., 'b' : 1., 'c' : 2.}
s = pd.Series(dictData.values(), index=[0,1,2])
print(s)

0    0.0
1    1.0
2    2.0
dtype: float64


In [21]:
dictData = {'a' : 0., 'b' : 1., 'c' : 2., 'd': 2}

s = pd.Series(dictData.keys(), index=dictData.values())
print(s)

0.0    a
1.0    b
2.0    c
2.0    d
dtype: object


In [22]:
dictData = {'a' : 0., 'b' : 1., 'c' : 2., 'd': 2}
s = pd.Series(dictData.keys(), index=[0,1,2,2])
print(s)

0    a
1    b
2    c
2    d
dtype: object


In [23]:
listData = [34, 21, "40", 7.9]

ser = pd.Series(data=listData)

print(ser)

0     34
1     21
2     40
3    7.9
dtype: object


In [24]:
ser = pd.Series(data = listData, name="SeriesFromList")
ser

0     34
1     21
2     40
3    7.9
Name: SeriesFromList, dtype: object

In [25]:
ser.name

'SeriesFromList'

In [26]:
ser.index

RangeIndex(start=0, stop=4, step=1)

In [27]:
intArr = np.arange(10)
ser = pd.Series(data=intArr, index=['a', 'b','c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print(ser.index)

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')


In [28]:
ser.values

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
ser.to_numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# Access to the first index in Series

print("By 'a' index : ", ser["a"])
print("By 0 index : ", ser[0])

By 'a' index :  0
By 0 index :  0


In [31]:
ser.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

In [32]:
ser[0:6]

a    0
b    1
c    2
d    3
e    4
f    5
dtype: int32

In [33]:
ser[0:6:2]

a    0
c    2
e    4
dtype: int32

In [34]:
ser['a':'i']

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
i    8
dtype: int32

In [35]:
ser = pd.Series(data = [10, 20,30], index=[1, 5 , 68])
ser

1     10
5     20
68    30
dtype: int64

In [37]:
ser[1]

10

In [38]:
ser.values

array([10, 20, 30], dtype=int64)

In [39]:
ser>5

1     True
5     True
68    True
dtype: bool

In [41]:
ser[ser>10]

5     20
68    30
dtype: int64

In [42]:
print("Mean value : ", ser.mean())

Mean value :  20.0


In [43]:
print("Standard Deviation : ", ser.std())

Standard Deviation :  10.0


In [44]:
np.array([100,200,300,400,500]).std()

141.4213562373095

In [45]:
print("Quantiles values : ")
print("Q1 : ", ser.quantile(0.25))
print("Q2 : ", ser.quantile(0.50))
print("Q3 : ", ser.quantile(0.75))

Quantiles values : 
Q1 :  15.0
Q2 :  20.0
Q3 :  25.0


In [49]:
ser

1     10
5     20
68    30
dtype: int64

In [50]:
1 in ser

True

In [51]:
10 in ser

False

In [52]:
#######################################################################

In [53]:
df = pd.DataFrame()

In [56]:
df

Empty DataFrame
Columns: []
Index: []

In [57]:
data_1 = [["karam",78],['ali',67],['rand',45],['hasn',80]  ]
data_1

[['karam', 78], ['ali', 67], ['rand', 45], ['hasn', 80]]

In [58]:
df=pd.DataFrame(data=data_1 , columns=['name','gpa'])
df

name  gpa
0  karam   78
1    ali   67
2   rand   45
3   hasn   80

In [60]:
data_2= [ [10,12] , [14,13],[15,7],[10,2],[19,16]   ]
df2=pd.DataFrame(data=data_2  ,columns=['s1','s2'])
df2

s1  s2
0  10  12
1  14  13
2  15   7
3  10   2
4  19  16

In [61]:
data={  "name":['Ali','Khaled','omar','sanad','rami']  ,
      "age":[34,22,19,12,53]}
df=pd.DataFrame(data)
df

name  age
0     Ali   34
1  Khaled   22
2    omar   19
3   sanad   12
4    rami   53

In [62]:
data=  [ {'a':10,'b':7 ,'c':8}, {'a':6,'b':7,'c':5},{'a':4,'b':4,'c':9}  ]
df=pd.DataFrame(data)
df

a  b  c
0  10  7  8
1   6  7  5
2   4  4  9

In [63]:

d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
   'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(data = d)

In [64]:
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [65]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
   'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(data = d)
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [66]:
df["three"] = pd.Series([10,20,30],index=['a','b','c'])

In [67]:
df

one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [68]:
df["four"] = 4

In [69]:
df

one  two  three  four
a  1.0    1   10.0     4
b  2.0    2   20.0     4
c  3.0    3   30.0     4
d  NaN    4    NaN     4